### ISSUE TITLE
Use base class in a new vector class

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#1154]
Can I have some advice on a new vector class that includes a base class? When the `yearmonth` class isn't subclassing `Date`, `vec_arith()` works as expected. However, if including `Date`, it skips the defined `vec_arith()` method, and directly calls `+.Date`. Thanks.

``` r
library(vctrs)
# working as expected
new_yearmonth <- function(x = double()) {
  new_vctr(new_date(x), class = "yearmonth")
}

vec_arith.yearmonth <- function(op, x, y, ...) {
  UseMethod("vec_arith.yearmonth", y)
}

vec_arith.yearmonth.numeric <- function(op, x, y, ...) {
  if (op == "+") {
    new_date(new_yearmonth(0)) + lubridate::period(month = y)
  }
}

new_yearmonth(0) + 1
#> [1] "1970-02-01"

# subclassing Date, not working as expected
new_yearmonth <- function(x = double()) {
  new_vctr(new_date(x), class = c("yearmonth", "Date"))
}

vec_arith.yearmonth.numeric <- function(op, x, y, ...) {
  if (op == "+") {
    new_date(new_yearmonth(0)) + lubridate::period(month = y)
  }
}

new_yearmonth(0) + 1
#> [1] "1970-01-02"
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
When you inherit from Date as above, the class structure becomes:

```r
> class(new_yearmonth(0))
[1] "yearmonth"  "Date"       "vctrs_vctr"
```

Base R defines `+.Date`, so that gets called before our `+.vctrs_vctr` method, which is what hands off to `vec_arith()`. This is why you see the behavior above.

I'd imagine that the class structure would have to be forced as this to work as you intend:

```
c("yearmonth", "vctrs_vctr", "Date")
```

However, I'm not sure that inheriting from Date is generally a good idea, since it probably wasn't designed with extensibility in mind.

I've also worked on a ymon class, after being inspired by yours, that outlines exactly how I'd see it interacting with vctrs. It might be useful as a reference https://github.com/DavisVaughan/datea

**Comment by earowang** [comment]
Does it mean that inheriting from base type is discouraged from {vctrs}?

My `yearmonth` class works fine with all operations like casting and arithmetics, etc. But when using with ggplot2 for scales, a weird issue occurred to `yearmonth` but not `yearweek`, both of which share similar implementation. I couldn't figure out why.

Conceptually, `yearmonth` is a special class of `Date`. Before {vctrs}, subclassing `Date` was how I implemented. I didn't have to provide additional `scale_x_yearmonth()`, because `scale_x_date()` did the job for nice breaks and pretty formats. Without inheriting from `Date`, I'd copy lots of code from `scale_x_date()` and tweak for `yearmonth`, which isn't ideal.

**Comment by earowang** [comment]
@DavisVaughan Thanks for providing the reference. The {datea} doesn't have issues with ggplot2 scales. I'll dig more into it.

I'll leave this issue open, as I'd be interested to know if inheriting from base type is part of the roadmap of {vctrs} in general.

**Comment by lionel-** [comment]
> Does it mean that inheriting from base type is discouraged from {vctrs}?

Inheriting from the base type means inheriting from `integer`, `double`, `list`, etc. Here you are inheriting from a foreign class that doesn't explicitly provide a subclassing constructor. We're generally avoiding this pattern because and consider it undefined behaviour.

What are your goal for inherting from `Date`?

- Are there specific methods you'd like to dispatch to? Will these methods preserve your type correctly?
- If it's about making your class compatible with functions taking `Date` objects, I think the right way is for these functions to call either `as.Date()` or `vec_cast(x, <Date>)` on their inputs.

**Comment by earowang** [comment]
Thanks for correcting me that `Date` is a foreign class.

My primary goal for inheriting from `Date` is to use `ggplot2::scale_x_date()` rather than creating my own sets of `scale_x_*()`. Although I've already implemented those scaling functions by calling `as.Date()` for casting, there's a weird issue on the graphical axis, which wasn't an issue when subclassing `Date` before. I haven't figured out if the issue lies in ggplot2, vctrs, or my own implementation.

Please feel free to close the ticket.
