### ISSUE TITLE
Make vec_size() and vec_slice() generic

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#124]
Since these expose the fundamental interface to vectors

**Comment by hadley** [comment]
This is harder than I thought because we need to think through how to make an efficient C function generic. I'll leave for the next release

**Comment by hadley** [comment]
Note this will simplify the implementation of `vec_type.default()`, but `vec_type()` still needs to be generic.

**Comment by krlmlr** [comment]
Do we want `vec_meta()` for tibbles (https://github.com/tidyverse/tibble/issues/521)? Treating tibbles like "regular" columns will help avoid many special cases elsewhere.

For this, the C implementation should be an equivalent of a closure, because the C function that implements `vec_slice()` needs to know how to slice each individual component of a tibble (which could be another tibble or a matrix).
