### ISSUE TITLE
Should casting be stricter?

### ISSUE THREAD

**Issue by tjtnew** [r-lib/vctrs#1307]
Consider the following simple class:
```
testy <- function(x = double()) new_vctr(x, class = "testy")
```

As the underlying class is double, `vec_cast(1.5, new_test())` will work even if I have not defined a `vec_cast.testy.double` function.  This means if I want to hide the underlying class from the user I cannot just provide the method 
```
vec_cast.testy.default <- function(x, ...) vec_cast(x, testy())
```
instead I will need to explicitly block the cast.  This may be what was intended, and be for a good reason, but it wasn't what I was naively expecting so I just wanted to provide feedback.

**Comment by DavisVaughan** [comment]
This is due to this fallback in `vec_default_cast()` that call `vctr_cast()` https://github.com/r-lib/vctrs/blob/33eb948d2bc328c0d62c0ccf4812816fc97a067c/R/cast.R#L119-L121

Where `vctr_cast()` here calls `vec_restore()` to try and "restore" the double to a "testy" object.
https://github.com/r-lib/vctrs/blob/33eb948d2bc328c0d62c0ccf4812816fc97a067c/R/type-vctr.R#L140-L153

This `vctr_cast()` fallback will eventually be removed, so I would not rely on it to work. - it is noted here https://github.com/r-lib/vctrs/issues/968#issuecomment-670446511
