### ISSUE TITLE
Add `df_size_common(df, keep_empty = TRUE)`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1391]
While working on a [PR in `tidyr`](https://github.com/tidyverse/tidyr/pull/1126) to improve the performance of `unchop()` I thought that a "rowwise" version of `vec_size_common()` might be nice to export, e.g. `df_size_common(df, keep_empty)`. 

It would basically be the same as `purrr::pmap_int(df, vctrs::vec_size_common)` with an extra `keep_empty` argument.

``` r
library(vctrs)
library(tibble, warn.conflicts = FALSE)

df <- tibble(
  x = 1:3,
  y = list(
    NULL,
    tibble(a = 1, b = 2),
    tibble(a = 1:3, b = 3:1)
  )
)

purrr::pmap_int(df, vec_size_common)
#> [1] 1 1 3
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DavisVaughan** [comment]
I haven't seen this come up anywhere outside that tidyr PR, and the `keep_empty` argument is fairly specific to tidyr, so for now I'd like to close this and come back to the idea if it appears in more places. Since we've vectorized these calculations over in https://github.com/tidyverse/tidyr/pull/1140, I don't think the performance we'd get from this is quite as important anymore
