### ISSUE TITLE
Add `vec_interleave()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1396]
In `tidyr::pivot_longer()` it is at one point necessary to "interleave" a vector resp. fill its value into a matrix by row and then convert it back to a vector

```r
idx <- matrix(seq_len(nrow(data) * length(val_cols)), ncol = nrow(data), byrow = TRUE)
vec_slice(out, as.integer(idx))
```

or with a more concrete example

``` r
idx <- matrix(1:10, ncol = 2, byrow = TRUE)
vctrs::vec_slice(1:10, as.integer(idx))
#>  [1]  1  3  5  7  9  2  4  6  8 10
```

For big data this is very inefficient:

* surprisingly `matrix(x, byrow = TRUE)` is quite a bit slower than `t(matrix(x))`
* it is quite memory and time intensive just to create the index.

In [this discussion](https://github.com/tidyverse/tidyr/pull/1132#discussion_r653864349) Hadley brought up that it might make sense to move this to `vctrs` (even though it might be rare).

> Do you think it's worth pulling this out into an `interleave` function? I'm not sure this comes up very often, but we could also move into vctrs and consider our own C implementation (which I think should be fairly straight forward)

What do you think?

PS: I already asked Hadley about it but maybe you are rather the experts here. Do you have any idea if there would be any performance benefit if instead of using `vec_slice()` to reorder a vector like in this case there were a function `vec_reorder()` that only reorders the elements of it? I could imagine `vec_reorder()` to be more efficient but I don't know much about C code and the vctrs internals.

**Comment by DavisVaughan** [comment]
We had a basic sketch of it here
https://github.com/tidyverse/funs/issues/10#issuecomment-832568731

A C implementation would be pretty similar, replacing the `matrix(byrow)` line.

It's also possible that it would be faster to use a single `vec_unchop()` call rather than `vec_c() + vec_slice()`. I'm not sure though, since with `vec_unchop()` you have to build a list of indices and that might be more expensive than the current approach.
