### ISSUE TITLE
Explore SIMD and parallel optimisations

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#14]
Via RcppParallel and/or RcppArmadillo

**Comment by lionel-** [comment]
I've been thinking about this as well. One downside in current dplyr's evaluation scheme is that the hybrid handlers are called with unsorted data and a vector of indices. This impedes memory locality and thus creates cache misses. It also makes it more difficult to use threads.

So I think C grouped eval should use the same scheme as R grouped eval: copy the data to a shrinkable vector (this avoids sexp allocation overhead by reusing a single sexp of variable size) and call the handler with this contiguous vector. Since this is a copy of the original R vector, the handler can modify it directly. And finally we copy it back to the unsorted data (in the case of `mutate()`).

Memory locality should improve cache access but maybe we can go further. If we detect a hybrid handler, we could instantiate `ncores` temporary shrinkable vectors and call the handlers in their own thread to get parallelisation. And the day R becomes thread safe we can immediately apply the same strategy for R evals.

**Comment by lionel-** [comment]
Also, the temporary vectors should not only be shrinkable but expandable as well because for array mapping we need to handle results that are larger than the original dimension size (t cross products etc). This also means that we should decouple evaluation and result form checking. And this will then make it easy to create variants of `summarise()` that accept variable length vectors or that spread the results over columns.

I'm thinking that it'd be a good time to think about a rcpp-lite package that would provide simple c++ data structures. They would all be shrinkable and expandable just as STL containers. The focus of this package would be on c++ idioms rather than R idioms, which should allow it to stay relatively simple. For example the brackets operator would be an extracting operation rather than a subsetting one.

**Comment by krlmlr** [comment]
Up to two extra copies for improving cache locality sounds like a bad deal to me. In which cases would this actually improve overall performance (assuming near-uniform memory access costs for all CPUs)?

**Comment by lionel-** [comment]
> Up to two extra copies for improving cache locality sounds like a bad deal to me.

There is only one extra copy but yes we'd have to measure performance trade-offs.

**Comment by krlmlr** [comment]
> And finally we copy it back to the unsorted data

made me think it may be two copies, but anyway.

**Comment by lionel-** [comment]
this copy is already there, you have to map from the resulting sexp to the full output vector for a mutating op. The idea is also to simplify the code, we'd want the hybrid handlers to work with any expression as arguments, including nested hybrid handlers, not just with symbols. This means we need to evaluate the arguments and store the result in a temp buffer.

We can always optimise for the case of a symbol, but I think it'd be nice if the handler would get a pair of iterators as arguments. That's possible with non local memory but then you'd have to write special iterators.

Just tried some benchmark for computing averages, performance with copy is similar for a `1e7` long vector with 100 groups. Performance disparity gets worse as `n` shrinks.

```c++
struct is_na_ {
  bool operator() (double& x) { return std::isnan(x); }
  bool operator() (int& x) { return x == NA_INTEGER; }
};

template <typename T>
bool is_na(T x) {
  return is_na_()(x);
}

template <typename T, typename I>
I remove_copy_na(T x, I out_first) {
  return std::remove_copy_if(std::begin(x), std::end(x), out_first, is_na_());
}
template <typename I, typename O>
O remove_copy_na(I first, I end, O out_first) {
  return std::remove_copy_if(first, end, out_first, is_na_());
}

// Copy NA's at the end before computation
template <typename T>
double functor1(T x) {
  T copy(x.size());
  auto copy_end = remove_copy_na(x.begin(), x.end(), copy.begin());
  int n = std::distance(copy.begin(), copy_end);
  double sum = std::accumulate(copy.begin(), copy_end, 0.0);
  return sum / n;
}


struct plus_na_ {
  template <typename T1, typename T2>
  auto operator()(const T1 &lhs, const T2 &rhs) const
      -> decltype(lhs + rhs) {
    if (!is_na(rhs))
      return lhs + rhs;
    else
      return lhs;
  }
};

// Check for NAs during sum
template <typename T>
double functor2(T x) {
  double sum = std::accumulate(std::begin(x), std::end(x), 0.0, plus_na_());
  return sum / x.size();
}
```

```{r}
make_x <- function(n, na = TRUE) {
  vec <- rnorm(n, sd = 20)
  if (na) {
    index <- sample(seq_along(vec), ceiling(n/2))
    vec[index] <- NA
  }
  vec
}

n <- 1e7
j <- 100
df <- data_frame(
  x_na = make_x(n),
  x = make_x(n, FALSE),
  g = sample(seq_len(j), n, TRUE)
)
grouped_df <- group_by(df, g)
```

Ungrouped (thus no extra copy):

```{r}
(mb <- microbenchmark::microbenchmark(times = 50,
  functor1 = functor1(df$x),
  functor2 = functor2(df$x),
  dplyr = summarise(df, mean(x, na.rm = TRUE))
))
#> neval: 50
#>       expr median         unit
#> 1 functor1     50 milliseconds
#> 2 functor2     13 milliseconds
#> 3    dplyr    151 milliseconds

(mb_na <- microbenchmark::microbenchmark(times = 50,
  functor1 = functor1(df$x_na),
  functor2 = functor2(df$x_na),
  dplyr = summarise(df, mean(x_na, na.rm = TRUE))
))
#> neval: 50
#>       expr median         unit
#> 1 functor1     69 milliseconds
#> 2 functor2     47 milliseconds
#> 3    dplyr    229 milliseconds
```

Grouped:

```r
grouped_apply <- function(df, fun, var = "x") {
  indices <- map(attr(df, "indices"), `+`, 1)
  purrr::map(indices, function(i) fun(df[[var]][i]))
}

(mb_grouped <- microbenchmark::microbenchmark(times = 50,
  functor1 = grouped_apply(grouped_df, functor1),
  functor2 = grouped_apply(grouped_df, functor2),
  dplyr = summarise(grouped_df, mean(x, na.rm = TRUE))
))
#> neval: 50
#>       expr median         unit
#> 1 functor1    539 milliseconds
#> 2 functor2    477 milliseconds
#> 3    dplyr    489 milliseconds

(mb_grouped_na <- microbenchmark::microbenchmark(times = 50,
  functor1 = grouped_apply(grouped_df, functor1, var = "x_na"),
  functor2 = grouped_apply(grouped_df, functor2, var = "x_na"),
  dplyr = summarise(grouped_df, mean(x_na, na.rm = TRUE))
))
#> neval: 50
#>       expr median         unit
#> 1 functor1    569 milliseconds
#> 2 functor2    528 milliseconds
#> 3    dplyr    531 milliseconds
```

With 1000 rows, the functors are still faster on ungrouped data, but the current hybrid handler is faster with grouped data, probably due to copy cost.

Ungrouped, no missings:

```
neval: 50
      expr median         unit
1 functor1     48 microseconds
2 functor2     39 microseconds
3    dplyr    451 microseconds
```

Ungrouped, missings:

```
neval: 50
      expr median         unit
1 functor1     41 microseconds
2 functor2     37 microseconds
3    dplyr    393 microseconds
```

Grouped, no missings:

```{r}
neval: 50
      expr median         unit
1 functor1   2465 microseconds
2 functor2   2505 microseconds
3    dplyr    622 microseconds
```

Grouped, missings:

```{r}
neval: 50
      expr median         unit
1 functor1   2355 microseconds
2 functor2   2336 microseconds
3    dplyr    592 microseconds
```

**Comment by hadley** [comment]
I think we'd probably want to couple this with a version of `group_by` that sorts the data

**Comment by hadley** [comment]
I'm going to close this for now, since I think we're still along way off for worrying about this.
