### ISSUE TITLE
vec_set_names(names = NULL) creates invalid rcrd

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#1419]
``` r
library(vctrs)

rcrd <- new_rcrd(data.frame(a = 1:3))
unnamed_rcrd <- vec_set_names(rcrd, NULL)
field(rcrd, "a")
#> [1] 1 2 3
field(unnamed_rcrd, "a")
#> Error: Corrupt x: no names
waldo::compare(rcrd, unnamed_rcrd)
#> `names(old)` is character ('a')
#> `names(new)` is absent
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

Do we need `validate_rcrd()` too, and perhaps `format.rcrd()` that delegates to pillar if it's installed?

**Comment by DavisVaughan** [comment]
Currently, the rcrd types the come out-of-the-box from vctrs don't support names. We have a `names.vctrs_rcrd` method that just returns `NULL`, but we don't have a `names<-.vctrs_rcrd` method, so it just uses the default `names<-` for a list which is removing the field names.

We might want to consider defining a temporary `names<-.vctrs_rcrd` method like:

```r
`names<-.vctrs_rcrd` <- function(x, value) {
  if (is.null(value)) {
    x
  } else {
    abort("Can't assign names to a <vctrs_rcrd>.")
  }
}
```

This would be like `row.names<-.tbl_df` in that it is a no-op when trying to clear the names, but otherwise fails.

In the long term, I believe we would like to fully support names for vctrs-rcrd types. I have done so in clock, and it works fairly well, I think:

``` r
library(clock)

x <- year_month_day(2019, 1, 1)

# Calls clock:::`names<-.clock_rcrd`
x <- vctrs::vec_set_names(x, "a")
x
#> <year_month_day<day>[1]>
#>            a 
#> "2019-01-01"

# Calls clock:::names.clock_rcrd
names(x)
#> [1] "a"
vctrs::vec_names(x)
#> [1] "a"

# Clear them
vctrs::vec_set_names(x, NULL)
#> <year_month_day<day>[1]>
#> [1] "2019-01-01"
```

**Comment by krlmlr** [comment]
Thanks for the heads up. There' no rush, I have worked around in tibble.
