### ISSUE TITLE
Internal errors reports wrong package

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1561]
Someone just sent me this:

```
Error in `vec_rbind()`:
! Unexpected `NULL`.
ℹ In file slice.c at line 322.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error in the rlang package, please report it to the package authors.
Backtrace:
    ▆
 1. ├─dplyr::bind_rows(mod_sum_all, mod_sum_temp)
 2. │ └─vctrs::vec_rbind(!!!dots, .names_to = .id)
 3. └─rlang:::stop_internal_c_lib(...)
 4.   └─rlang::abort(message, call = call, .internal = TRUE)
```

We shouldn't direct users towards rlang here. Hopefully we can do better.

**Comment by DavisVaughan** [comment]
Do you mean to pass the `caller` through here?

https://github.com/r-lib/rlang/blob/0e9e6455150f893c46e2b0d564f26c5a4b097d65/R/cnd-abort.R#L304

That `caller` argument becomes `env` in `cnd_message_info()` and ends up getting used to build the footer here:
https://github.com/r-lib/rlang/blob/0e9e6455150f893c46e2b0d564f26c5a4b097d65/R/cnd-abort.R#L587

But since `caller` is just the `caller_env()` that `abort()` is called from, it will always say it is in rlang because `abort()` is called from `rlang:::stop_internal_c_lib()`.

The `call` argument that comes through `abort()` has the right information in it, so it is definitely available at abort time. Maybe that can be used instead to build the footer somehow?

**Comment by lionel-** [comment]
I thought about adding a separate `caller` arguments or allowing `call = list(call, caller = frame)`. For that specific case maybe we should accept `.internal = frame`. Stack handling is so complex.

**Comment by lionel-** [comment]
Upstream issue: https://github.com/r-lib/rlang/issues/1386

**Comment by lionel-** [comment]
Fixed by https://github.com/r-lib/rlang/commit/a8723e8ae6ecfa21e388591fda6018d1c2608c6a
