### ISSUE TITLE
`vec_ptype(NA)` vs `vec_ptype_common(NA, NA)`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1575]
I guess it's not a big issue but I don't know whether it makes sense that `vec_ptype()` and `vec_ptype_common()` produce different results:

``` r
library(vctrs)

vec_ptype(NA)
#> <unspecified> [0]
vec_ptype2(NA, NA)
#> <unspecified> [0]
vec_ptype_common(NA, NA)
#> logical(0)
```

<sup>Created on 2022-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
I'm fairly certain the `vec_ptype2()` vs `vec_ptype_common()` behavior was intentional, with the intention being that `vec_ptype2()` is used when computing the common type by doing something like `reduce(xs, vec_ptype2)`, so it needs to propagate the unspecified-ness, but right before we return the final common type we "finalize" it with `vec_ptype_finalize()` to turn unspecified into `logical()`

I'm not quite so sure about what `vec_ptype(NA)` should return (unspecified vs logical). I know there has been at least 1 time where I've had to manually call `vec_ptype_finalize()` after calling `vec_ptype()` to turn the unspecified into a logical, so maybe it should be treated as a "final" type too, but I'm not certain

**Comment by lionel-** [comment]
Regarding finalisation, there is some discussion in https://vctrs.r-lib.org/reference/internal-faq-ptype2-identity.html.

I think conceptually `vec_ptype2()` operates on the `vec_ptype()` of a vector, so the latter should propagate unspecifiedness.

**Comment by DavisVaughan** [comment]
Oh good point about `vec_ptype2()` using `vec_ptype()`, that logic seems correct to me
