### ISSUE TITLE
Additional arg for `vec_detect_missing()`/`vec_detect_complete()` so they can mirror each other

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/vctrs#1739]
Is it possible to add an argument to `vec_detect_missing()` and `vec_detect_complete()` so that they can optionally mirror each other when used on data frames?

I was surprised by the fact that these returns were different (though I did find that the difference is documented).

``` r
library(vctrs)

df <- data_frame(x = c(1, NA, 3), y = c(NA, 2, 3))

vec_detect_complete(df)
#> [1] FALSE FALSE  TRUE

!vec_detect_missing(df)
#> [1] TRUE TRUE TRUE
```

**Comment by DavisVaughan** [comment]
These are intentionally different, and are intended to represent two difference concepts:

- missingness: A row of a data frame is _missing_ if _all_ elements in that row are missing.
- incomplete: A row of a data frame is _incomplete_ if _any_ elements in that row are missing.

So we don't really want a way to make them equivalent, because they represent different things
