### ISSUE TITLE
Obscure CRAN error 

### ISSUE THREAD

**Issue by dieghernan** [r-lib/vctrs#1821]
Hi @DavisVaughan 

I see an obscure error on CRAN on some of my packages, I pressume due to the last release of vctrs. It is only in [r-devel-linux-x86_64-debian-gcc](https://cran.r-project.org/web/checks/check_flavors.html#r-devel-linux-x86_64-debian-gcc):

```r

> as_tibble(r, xy = TRUE)
    Error in vectbl_assign(x[[j]], cells[[j]], value) : 
     DLL requires the use of native symbols
    Calls: as_tibble ... tbl_subassign_matrix -> withCallingHandlers -> vectbl_assign
    Execution halted 

```

I see it in two packages:

https://cran.r-project.org/web/checks/check_results_tidyterra.html

https://cran.r-project.org/web/checks/check_results_climaemet.html

Weird thing is that I do not use vctrs directly, but dplyr on these. I would also cross-posted in dplyr.

Any clue?

**Comment by dieghernan** [comment]
Seen also in:

- https://cran.r-project.org/web/checks/check_results_eyelinker.html
- https://cran.r-project.org/web/checks/check_results_nflseedR.html
- https://cran.r-project.org/web/checks/check_results_googledrive.html

And some more, not posting all of them

**Comment by lionel-** [comment]
I don't think this is due to vctrs, but to this change in r-devel: https://github.com/r-devel/r-svn/commit/ae6f1becea792745847c227f2e92ebca2999f875

It's currently guarded behind an envvar and it looks like they turned it on on CRAN to assess the breakage fallout. Looks like some package in the stack sets `R_forceSymbols(dll, TRUE)` but that isn't vctrs.

But really I don't understand the r-devel change. It would make more sense to me if they checked whether `R_forceSymbols` was set to `FALSE`, not to `TRUE`. I'd suggest to just wait and see what happens next on r-devel.

**Comment by DavisVaughan** [comment]
@lionel- I think Kirill fixed it anyways https://github.com/tidyverse/tibble/commit/f9b27ae077e67f1e4871084eedee71a57bb372c7

**Comment by msberends** [comment]
Also ran into this (and fearing with great fears the potentially immediate archival mail from Ripley…). 

The checks of the `tibble` package are much more informative: https://cran.r-project.org/web/checks/check_results_tibble.html

Great to see action here already, many thanks for the work done.
