### ISSUE TITLE
Generic predicates should operate on proxy but not restore

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#251]
They probably should always return an untyped bool.

```r
new_cached_sum <- function(x = double(), sum = 0L) {
  new_vctr(x, sum = sum, class = "vctrs_cached_sum")
}
vec_restore.vctrs_cached_sum <- function(x, to, ..., i = NULL) {
  new_cached_sum(x, sum(x))
}
x <- new_cached_sum(runif(10))

is.finite(x)
#> <vctrs_cached_sum[10]>
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

**Comment by DavisVaughan** [comment]
This might be rray specific, but still seems relevant. Should this return an untyped logical matrix? It seems useful to still return an rray because you might want to do other operations on it that require the overloads on `+` or `*` or whatever that perform broadcasting.

``` r
library(rray)
rray(1:2, c(2, 1)) > 1
#> <rray<lgl>[,1][2]>
#>       [,1]
#> [1,] FALSE
#> [2,]  TRUE
```

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
