### ISSUE TITLE
vec_order() vec_sort() for bit64::integer64

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#348]
``` r
suppressPackageStartupMessages(library(bit64))
library(vctrs)

x <- bit64::as.integer64(-c(1, 3, 2, 1))
vec_order(x)
#> [1] 1 2 3 4
x[vec_order(x)]
#> integer64
#> [1] -1 -3 -2 -1
vec_sort(x)
#> integer64
#> [1] -1 -3 -2 -1
```

This is related to https://github.com/tidyverse/dplyr/issues/4366. 

Would this be the job of a `vec_proxy_compare.integer64` method ?

**Comment by lionel-** [comment]
I think this is more difficult than it first appears. Negative int64 numbers are stored in the payload of `NaN` numbers. They need to be reinterpreted as integers before any arithmetic of comparison operation is performed.

One approach is to cast to double in the proxy. This would be slow because of the back and forth conversion and would restrict the range of integers since `double` can't store as many numbers as `int64_t`.

Another approach would be to instrument the proxy with operator overloads. The proxy would carry C pointers in its attributes pointing to overloads for `<`, `+` etc. It's possible that it'd also make sense for the ALTREP framework to allow overloading these operators.

These issues/solutions will also be relevant for our own int64 vctrs type that we'll eventually implement (probably on top of a RAWSXP).

cc @kevinushey and @jimhester

**Comment by lionel-** [comment]
For performance the overloads should take pointers and sizes, not scalars.

**Comment by jimhester** [comment]
Why can't you just delegate to `bit64::order.integer64`?

**Comment by lionel-** [comment]
This would require changing how genericity works in vctrs.

**Comment by jimhester** [comment]
Ok different question, why isn't `vec_order()` a generic with the default method being the current definition.

**Comment by lionel-** [comment]
That would work, but `vec_compare()` and other functions that would otherwise use the comparison proxy would also need to become generic. In vctrs we're trying to reduce the number of customisation points to a minimum, if possible and reasonable.

**Comment by jimhester** [comment]
Ok, after looking at the code a bit I think I now get it, what about this.

``` r
vec_proxy_compare.integer64 <- function(x, ..., relax = FALSE) {
  bit64::rank.integer64(x)
}

suppressPackageStartupMessages(library(bit64))
library(vctrs)

x <- bit64::as.integer64(-c(1, 3, 2, 1))
vec_order(x)
#> [1] 2 3 1 4
x[vec_order(x)]
#> integer64
#> [1] -3 -2 -1 -1
vec_sort(x)
#> integer64
#> [1] -3 -2 -1 -1
```

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
oh nice! That's much better than converting to double. It would be nice to avoid the intermediate representation, since those are big vectors, but that can be solved later. About the idea of overloading C operators, it might be possible for ALTREP with some modifications in R but probably not in vctrs.
