### ISSUE TITLE
`vec_c()` & `vec_rbind()` not working for integer dates & datetimes

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#396]
Can integers be acceptable for `new_date()` and `new_datetime()`? Running into issues when `vec_rbind()`. `is.double(x)` is a bit too strict for date & datetime.

``` r
library(vctrs)
as.Date(18055L, origin = "1970-01-01")
#> [1] "2019-06-08"
new_date(18055)
#> [1] "2019-06-08"
new_date(18055L)
#> Error in new_date(18055L): is.double(x) is not TRUE
```

<sup>Created on 2019-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
Use case:

``` r
library(vctrs)
new_date(seq(Sys.Date(), length.out = 3, by = 1))
#> Error in new_date(seq(Sys.Date(), length.out = 3, by = 1)): is.double(x) is not TRUE
```

<sup>Created on 2019-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I think this implies a helper is needed that calls `vec_cast()` https://adv-r.hadley.nz/s3.html#helpers

**Comment by earowang** [comment]
Thanks, it makes sense for constructors to be strict. See my updated examples. I don't have a new custom class, but running issues into `vec_rbind()` and `vec_c()`.

**Comment by DavisVaughan** [comment]
For the `vec_c()` issue, here is the issue:

- `vec_c()` is given _integer_ dates
- It calls `vec_type_common(date[1], date[2:3])` internally to get `ptype`, which returns a _double_ date because of `vec_type2.Date.Date()`
- It casts each input to the `ptype`, but the integer dates stay integers
- The `out` container is created using the ptype, which is a _double_ date
- `vec_assign_impl(out, i, elt)` is called, where `out` is a double date, and elt is an integer date
- The `dbl_assign()` function is called, which is what tries to call `REAL()` on the integer date

One solution is to have:

```
vec_cast.Date.Date <- function(x, to) {
  if (is.integer(x)) {
    x <- as.double(x)
    new_date(x)
  } else {
    x
  }
}
```

That way when the cast to the `ptype` is done, integer dates are converted to doubles. This would be consistent with the type returned from `vec_type_common(date, date)`.

We also have inconsistencies with the fact that `vec_type(date)` and `vec_type_common(date)` by themselves return integer dates.

Technically the `?Date` docs say: "It is intended that the date should be an integer, but this is not enforced in the internal representation. Fractional days will be ignored when printing."

**Comment by hadley** [comment]
`typeof(Sys.Date())` returns `double`, so I think we should treat the canonical type as `double`. But it seems like since base R function can produce integers we should handle both. I _think_ a minimal set change would be to automatically cast integers to doubles in `new_date()` and then `vec_cast.Date.Date` could return `new_date(x)`.

**Comment by DavisVaughan** [comment]
That's similar to what I was proposing but I don't think it is enough.

Because `vec_type()` will return an integer date if given an integer date, if we call `vec_c(date)` (different result from `vec_c(date, date)`) we will then be in a scenario where the `ptype` is an integer date, and the cast elements will all be doubles.

**Comment by hadley** [comment]
Ah yeah. In that case we probably have to wait until Date is implemented at the C level

**Comment by volemont** [comment]
fyi; there's a USD 200 bounty for this issue: https://www.bountysource.com/issues/75242571-vec_c-vec_rbind-not-working-for-integer-dates-datetimes
