### ISSUE TITLE
Only conditionally export tbl_df methods

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#437]
So that these methods can be gracefully taken over by the tibble package, without having to do another vctrs release.

@krlmlr

**Comment by lionel-** [comment]
I'm not sure we can do it without another release because tibble will need to use the C level extensibility to avoid the R dispatch overheads.

**Comment by krlmlr** [comment]
For starters, I'd like to take the `vec_type2()` methods to tibble. Would that be a problem?

Would the code on vctrs be simpler if we avoided the notion of a bare tibble altogether and delegated to `vec_restore()`?

**Comment by lionel-** [comment]
> Would the code on vctrs be simpler if we avoided the notion of a bare tibble altogether and delegated to vec_restore()?

The notion of a bare tibble plays very little role as it is. We'll be able to remove it once we have have C dispatch in:

* `vec_type2()`, the tibble method should wrap around the data frame method and then add its attributes.
* `vec_restore()`, which can just call the data frame method.

This makes me think it might be helpful to have an optional verbose mode to detect dispatch to R code.

> For starters, I'd like to take the vec_type2() methods to tibble.

Yes all of type-tibble.R should go. There should also be a `vec_cast.tbl_df()` method, which I see wasn't implemented yet. There is no `vec_restore.tbl_df()` method (relevant for subclasses of tibbles) because the default data frame method restores attributes. Grouped tibbles at least will need to override this.

**Comment by hadley** [comment]
If tibble has to use C extension points, then I think the methods will have to live in vctrs for some time to come. I don't want tibble to force us to develop a general extension mechanism too early.

**Comment by krlmlr** [comment]
I still don't see why C-level dispatch is necessary at this point. It might shave off a few microseconds here and there (can we measure it?), but I think separation of concerns is more important.

**Comment by lionel-** [comment]
Indeed it shouldn't be too bad unless you're row-binding 1000s of tibbles. I don't think separation of concerns is very important in the short term, we'll get there eventually. I would like to keep the tibble handling in vctrs for now because it shows where the customisation points are needed. Is there a practical reason for which you need to bypass the internal genericity?

**Comment by krlmlr** [comment]
I don't understand "bypass ...", can you please rephrase?

I suspect all tests still pass if we remove all mentions of `tbl_df` in the code (and in the tests)? If we do this, wouldn't we see the required customization points from the tibble implementation?

**Comment by lionel-** [comment]
We have internal genericity for bare tibbles, which prevents tibble from overriding the behaviour. Overriding the behaviour would normally be its prerogative because tibbles are the concern of the tibble package. You saidy you would like to have clear separation of concerns, so I'm asking if there is a practical reason for it, i.e. if you need to override behaviour in the short term.

> I suspect all tests still pass if we remove all mentions of tbl_df in the code (and in the tests)? If we do this, wouldn't we see the required customization points from the tibble implementation?

Yes they'd pass, thanks to the R methods. I'd like to keep the native methods because if we remove them it's less clear where the customisation points are needed in the data frame code. It's not essential since I can just go back in the git history, but I'd prefer to keep them for now.

**Comment by krlmlr** [comment]
No, I don't want to override the behavior. I have a vague feeling that moving it now to the right location will save a bit of pain in the medium term, perhaps because we won't have to deal with moving responsibilities and a state when both tibble and vctrs attempt to define the behavior.

Would you review a PR that adds `#defines`s so that we can at least measure the performance impact and also turn off easily?

**Comment by lionel-** [comment]
There won't be any issue of intermediate state. The intermediate state is just loss of efficiency because vctrs won't handle bare tibbles natively, and tibble won't either.

This is a different story for the R methods and I agree completely with Hadley that we need to conditionally export them.

**Comment by lionel-** [comment]
I cannot conditionally import the methods because loading tibble (and thus pillar) from `.onLoad()` causes the following CMD check warning:

```
W  checking S3 generic/method consistency (903ms)
   vec_ptype_abbr:
     function(x, ...)
   vec_ptype_abbr.pillar_empty_col:
     function(x)
   
   vec_ptype_abbr:
     function(x, ...)
   vec_ptype_abbr.pillar_empty_col:
     function(x)
   
   See section ‘Generic functions and methods’ in the ‘Writing R
   Extensions’ manual.
```

@krlmlr Can you send a fix to CRAN please?

**Comment by krlmlr** [comment]
{pillar} is on its way to CRAN.

**Comment by krlmlr** [comment]
On CRAN now.

**Comment by lionel-** [comment]
Thanks!
