### ISSUE TITLE
Promote integer and double to factor and character

### ISSUE THREAD

**Issue by patperry** [r-lib/vctrs#50]
Consider the use case of two CSV files, `a.csv` and `b.csv`, each with identical column names. One column is `id`. In `a.csv`, all `id` values are 10-digit codes. In `b.csv`, some `id` values contain letters. Concatenating the contents fails:

```r
a <- readr::read_csv("id\n12345678901")
b <- readr::read_csv("id\nX100000")
#> vec_c(a$id, b$id)
Error: No common type for double and character
```

**Comment by hadley** [comment]
In this case, I'd expect you to ask for a character:

``` r
library(vctrs)
a <- readr::read_csv("id\n12345678901")
b <- readr::read_csv("id\nX100000")

vec_c(a$id, b$id, .ptype = character())
#> [1] "12345678901" "X100000"

vec_rbind(a, b, .ptype = tibble::tibble(id = character()))
#> # A tibble: 2 x 1
#>   id         
#>   <chr>      
#> 1 12345678901
#> 2 X100000
```

In the long-run, the col types specification for readr and the ptype specification here will merge so you can either specify on load, or when combining with other datasets.

**Comment by jennybc** [comment]
I've encountered this, where I'm row binding csv's from an API and you gradually learn the full wonder/horror of what's possible. Is there a way to authorize taking the maximum type? Maybe this is a version of #48 🤔

**Comment by hadley** [comment]
I'm hoping we can tackle that by providing a "default" col-type a la readr (in the partial data frame type), and thinking a lot about the error message. Currently you get:

```
vec_rbind(a, b)
#> Error: No common type for double and character 
```

This is not useful because you don't get any context. I don't know how we're going to do this in general, but I'm imagining some output like this:

```R
#> Error: type coercion failed
#> Location Class     
#> a$id     double  
#> b$id     character
#> Specify type with `.ptype = col_types(id = list())`
```

It's going to be particularly challenging to figure out how to do this recursively - so that even when you're working deeply nested df- or list-cols you can still figure out the source of the error. I suspect generating an informative error message is going to be about as much work as the rest of the package put together 😑

**Comment by njtierney** [comment]
Just wanted to chime in to say that an informative error message like that would be super helpful - is this going to be implemented, in the long term?

**Comment by hadley** [comment]
Yes
