### ISSUE TITLE
Add basic data.table support

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#694]
So that `vec_cbind(data.table(), data.frame())` returns a data table — I think this fits in naturally to the container work that we're doing for this release.

**Comment by lionel-** [comment]
Coercing to a data table would mean that it's a super-type mixin of data.frame. I don't think this is right because data.table doesn't really implement data.frame. They seem to be different types entirely even though they share the same data structure. I think implementing these coercion semantics would make generic code in the ecosystem less robust.

**Comment by hadley** [comment]
I think it's just a difference of amount compared to tibble (i.e. tibbles aren't really data frames either). Both tibbles and data.tables implement the "core" of a data frame, so pragmatically, I think we have to treat them the same way.

**Comment by mik3y64** [comment]
I hope this issue gets resolved. Thank you. It affects`tidyr::nest()`, `drake::drake_plan()` and other downstream packages that use vctrs under the hood. Package developers or maintainers cannot do anything about it.
