### ISSUE TITLE
vec_sort(<POSIXlt>)

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#720]
``` r
library(vctrs)

dates <- as.POSIXlt(seq(as.Date("2019-12-30"), as.Date("2020-01-02"), by = "day"))
sort(dates)
#> [1] "2019-12-30 UTC" "2019-12-31 UTC" "2020-01-01 UTC" "2020-01-02 UTC"
vec_sort(dates)
#> [1] "2020-01-01 UTC" "2020-01-02 UTC" "2019-12-30 UTC" "2019-12-31 UTC"

# ok with POSIXct
dates <- seq(as.Date("2019-12-30"), as.Date("2020-01-02"), by = "day")
sort(dates)
#> [1] "2019-12-30" "2019-12-31" "2020-01-01" "2020-01-02"
vec_sort(dates)
#> [1] "2019-12-30" "2019-12-31" "2020-01-01" "2020-01-02"
```

<sup>Created on 2019-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by DavisVaughan** [comment]
I figured this would come up, I could never make a good example of it. I think this happens because the data frame proxy doesn’t have the components in the correct order for sorting purposes. We could convert to POSIXct for `vec_proxy_compare()` or maybe we could reorder the proxy data frame columns to be correct
