### ISSUE TITLE
Recycling data frames

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#77]
Should these recycle the data frame to length zero?

```r
shape <- vec_shape(integer())
vec_reshape(mtcars, shape)
#> Error: Can only recycle data frame along rows

shape <- vec_shape(matrix(nrow = 0, ncol = 1))
vec_reshape(mtcars, shape)
#> Error: Can only recycle data frame along rows

shape <- vec_shape(matrix(nrow = 0, ncol = 0))
vec_reshape(mtcars, shape)
#> Error: Can only recycle data frame along rows
```

Same for recycling 1-row dataframes to length n:

```r
shape <- vec_shape(integer(3))
vec_reshape(mtcars[1, ], shape)
#> Error: Can only recycle data frame along rows
```

Currently the dimensions have to match completely:

```r
shape <- vec_shape(matrix(nrow = 0, ncol = ncol(mtcars)))
vec_reshape(mtcars, shape)
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)

shape <- vec_shape(matrix(nrow = 3, ncol = ncol(mtcars)))
vec_reshape(mtcars[1, ], shape)
#>   mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> 1  21   6  160 110  3.9 2.62 16.46  0  1    4    4
#> 2  21   6  160 110  3.9 2.62 16.46  0  1    4    4
#> 3  21   6  160 110  3.9 2.62 16.46  0  1    4    4
```

Maybe that's because I need directional recycling instead of full shape recycling?

Maybe the errors could be a little more informative to help figure out why the recycling can't be done.

**Comment by hadley** [comment]
My reasoning here was that it only makes sense to recycle a data frame down the rows - you can't recycle columns because they have to have unique names. I think that's correct, even though it's rather restrictive. 

But maybe I should allow recycling a data frame with a one-dimensional shape, assuming that would match the number of rows? i.e. `vec_reshape(data.frame(x = 1, y = 2), vec_shape(integer(3))` would yield a 3 row data frame?

But it might be better to wait for the next version when I fully think through the interaction between shape and type: currently it's a bit murky.
