### ISSUE TITLE
vec_is and vec_assert_is

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#79]
```R
vec_is(1:10, integer())
# TRUE

vec_is(1:10, integer(2))
# FALSE

vec_assert_it(1:10, integer(2), name = "x")
# Error: `x` must be an integer vector of length 2, not an integer vector of length 10.
```

Requires thinking about the intersection of shape and type. Might be possible to delay general resolution of this issue by adding an `n` argument, or special-casing the use of length here.

**Comment by lionel-** [comment]
From Slack discussion:

* Still need `vec_is()`, for instance when we want different error messages than `vec_assert()`.

* `vec_assert()` would be more generally useful if it took the argument name as parameter instead of using NSE (so we could use it in checker functions extracted from main function).
