### ISSUE TITLE
class argument to bare-bones constructors

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#895]
Currently, `new_data_frame()` does extra work to append `"data.frame"` to the class vector and doesn't bother checking if it's already there. This adds extra work to users who want to restore the `"class"` attribute based on existing input: https://github.com/tidyverse/dplyr/pull/4947/files#diff-a0b5adc7fa33b56d5e47c2dd503860f2R132

``` r
class(vctrs::new_data_frame(list(), class = class(tibble::tibble())))
#> [1] "tbl_df"     "tbl"        "data.frame" "data.frame"
```

<sup>Created on 2020-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Should we:

- check if `"data.frame"` is part of the class and omit duplication if it's there
- expect callers to include `"data.frame"`
- keep doing extra work twice?

?

**Comment by DavisVaughan** [comment]
the fact that this is so difficult makes me wonder if we are trying to force `new_data_frame()` into a use case that it isn’t meant for

Perhaps `dplyr_reconstruct()` and `dplyr_col_modify()`, which both already take existing data frames, just need to use something like `vec_set_attributes()`, which could be tweaked to ensure we don’t expand compact row names like `attributes<-` does.

One downside is that `attributes<-` can use altrep to make a “wrapper” object to assign attributes to if the original object is any atomic type except for a list, which is cheaper, but that wouldn’t make a difference right now for data frames

On the other hand, I do think `new_tibble()` should continue to use `new_data_frame()`. It makes sense there because the child constructor should call the parent constructor before returning

**Comment by krlmlr** [comment]
Do we need better tooling for pairlists and attributes (https://github.com/r-lib/rlang/issues/940)?

`new_tibble()` never used `new_data_frame()`, I'd rather not change existing working code for a more complicated implementation at this time.

**Comment by krlmlr** [comment]
The original `dplyr_col_modify()` used `[.tbl_df()`, this works flawlessly for tibble >= 3.0.0. This means that once we release tibble we can rely on the infrastructure there.

**Comment by lionel-** [comment]
> check if "data.frame" is part of the class and omit duplication if it's there

I don't think so. Certainly not omit duplication, maybe throw an internal error.

> expect callers to include "data.frame"

This is not the recommended style for calling constructors. Callers of a constructor are supposed to only add their own classes.

**Comment by lionel-** [comment]
By the way I'm not sure I completely follow the larger context here, but if it's about restoring attributes in dplyr, maybe we should just put this on hold. Unless I'm mistaken we weren't restoring attributes previously, so I would rather wait longer than risk going in a wrong direction. I think attribute restoration will require a long dev period, and we are already late in the 1.0 cycle.

**Comment by krlmlr** [comment]
This particular issue is about our handling of the `class` argument in `new_data_frame()` . I think we should relax requirements here and allow an existing `"data.frame"` in the `class` argument, *because* it's a bare-bones constructor that's supposed to be fast. Otherwise we'll be doing `c(setdiff(x, "data.frame"), "data.frame")` instead of `x` in quite a few places.

The extra check is a lookup if the last array element equals `"data.frame"`, and avoid calling `vec_c()` if true. We could also iterate and make appearance at other positions an error.

`dplyr_col_modify()` can use `[<-.tbl_df()` once tibble 3.0.0 is out.

I agree that `new_data_frame()` should be used eventually by `new_tibble()` and perhaps not by `[.tbl_df()` and friends.

**Comment by lionel-** [comment]
I would rather do nothing, as in all other constructors. `abort()` won't prevent you from passing `class = "rlang_error"`, and that seems fine. We have never been bitten by this.

> dplyr_col_modify() can use [<-.tbl_df() once tibble 3.0.0 is out.

I think I really would prefer to wait before doing that. I don't want to rush this. It doesn't seem like a big deal to post-pone attribute restoration until dplyr 1.1.

**Comment by hadley** [comment]
> dplyr_col_modify() can use [<-.tbl_df() once tibble 3.0.0 is out.

It can't, because that doesn't handle the data frame case. But I think the current implementation in dplyr is fine. It might could be nice to eventually have a replacement for https://github.com/tidyverse/dplyr/blob/master/R/generics.R#L121-L125; but I think that would mostly be a variant of `attributes()` that didn't expand row.names, and was generally optimised for performance.

**Comment by DavisVaughan** [comment]
> a variant of attributes() that didn't expand row.names, and was generally optimised for performance.

These are my thoughts exactly!
