### ISSUE TITLE
vctrs_unspecified redundant method in type-integer64.R?

### ISSUE THREAD

**Issue by danhalligan** [r-lib/vctrs#952]
I have some methods to catch cases for `vctrs_unspecified` in my own code, for example something like:

```
#' @method vec_ptype2.myclass vctrs_unspecified
#' @export
vec_ptype2.myclass.vctrs_unspecified <- function(x, y, ...) x
```

I'm coming to the conclusion that it is impossible to get to these methods as unspecified cases are handled internally. If this assumption is correct (I'm not sure!) then, this represents a redundant line of code:

https://github.com/r-lib/vctrs/blob/71aedcf42d8fdedc2e3f344af18813d9cf71acff/R/type-integer64.R#L48

as evidenced by the fact that there's no [code coverage](https://codecov.io/gh/r-lib/vctrs/src/master/R/type-integer64.R#L48) for this line, even though tests should cover the case here:

https://github.com/r-lib/vctrs/blob/71aedcf42d8fdedc2e3f344af18813d9cf71acff/tests/testthat/test-type-integer64.R#L39

I'd like to know either way as it would clarify the case for unspecified for me.

**Comment by DavisVaughan** [comment]
I am not sure about the CRAN version, but in the dev version you definitely should not need unspecified methods. We are really trying to consider that an internal type.

We handle it internally here
https://github.com/r-lib/vctrs/blob/master/src/type2.c#L47

In fact, it looks like the presence of that method causes a bug with shaped int64+unspecified, because the method doesn't handle shaped objects (our default fallthrough would though).

```r
library(vctrs)
library(bit64)

x <- as.integer64(1:4)
dim(x) <- c(2, 2)

# Wrong
vec_ptype2(x, unspecified())
#> integer64
#> character(0)

# This is the correct result
vec_ptype(x)
#> integer64
#>      [,1] [,2]
```

What happens here is that the C level `vec_ptype2()` sees that `has_dim(x)` is true so is falls back to R level ptype2 dispatch before it has a chance to test if any input is unspecified. Then we hit the `vec_ptype2.integer64.vctrs_unspecified` method but that doesn't handle shaped inputs

**Comment by lionel-** [comment]
There's still a bunch of unspecified methods to remove from the codebase.
